# Generated by Django 5.1.4 on 2024-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrubHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Pizza', 'Pizza 🍕'), ('Burgers', 'Burgers 🍔'), ('Sushi', 'Sushi 🍣'), ('Desserts', 'Desserts 🍰'), ('Indian', 'Indian 🍛'), ('Chinese', 'Chinese 🥡'), ('Mexican', 'Mexican 🌮'), ('Salads', 'Salads 🥗'), ('Beverages', 'Beverages 🥤'), ('Seafood', 'Seafood 🦞'), ('BBQ', 'BBQ 🍖'), ('Pasta', 'Pasta 🍝'), ('Breakfast', 'Breakfast 🍳'), ('Ice Cream', 'Ice Cream 🍦'), ('Fruits', 'Fruits 🍉'), ('Coffee', 'Coffee ☕'), ('Steak', 'Steak 🥩'), ('Soup', 'Soup 🍜'), ('Tacos', 'Tacos 🌮'), ('Donuts', 'Donuts 🍩'), ('Cookies', 'Cookies 🍪'), ('Popcorn', 'Popcorn 🍿'), ('Sandwich', 'Sandwich 🥪'), ('Chicken', 'Chicken 🍗'), ('Beer', 'Beer 🍺'), ('Wine', 'Wine 🍷'), ('Cocktails', 'Cocktails 🍹')], max_length=100),
        ),
    ]
