# Generated by Django 5.1.4 on 2024-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrubHub', '0002_category_icon_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
