# Generated by Django 5.1.4 on 2024-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrubHub', '0002_rename_company_name_restaurant_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(max_length=13),
        ),
    ]
